main:
  pattern: /
  defaults: {_controller: BigsoftStoreBundle:Index:index}
products_list:
  pattern: /products
  defaults: {_controller: BigsoftStoreBundle:Product:list}
product_create:
  pattern: /product/create
  defaults: {_controller: BigsoftStoreBundle:Product:create}
