main:
  pattern: /
  defaults: {_controller: BigsoftStoreBundle:Index:index}
products_list:
  pattern: /products
  defaults: {_controller: BigsoftStoreBundle:Product:list}
product_create:
  pattern: /product/create
  defaults: {_controller: BigsoftStoreBundle:Product:create}
product_edit:
  pattern: /product/edit/{id}
  defaults: {_controller: BigsoftStoreBundle:Product:edit}
product_view:
  pattern: /product/view/{id}
  defaults: {_controller: BigsoftStoreBundle:Product:view}
product_delete:
  pattern: /product/delete/{id}
  defaults: {_controller: BigsoftStoreBundle:Product:delete}