parameters:
  bigsoft.mailing.from_address: 'admin@bigsoftstore.com'

services:
  bigsoft.validator.unique_title:
    class: Bigsoft\StoreBundle\Validator\Constraint\UniqueTitleConstraintValidator
    arguments: ['@doctrine']
    tags:
      - {name: validator.constraint_validator, alias: unique_title}
  bigsoft.twig.money_format:
    class: Bigsoft\StoreBundle\Twig\MoneyFormatExtension
    tags:
      - {name: twig.extension}
  bigsoft.cart:
    class: Bigsoft\StoreBundle\Service\Cart
    arguments: ['@doctrine', '@session']
  bigsoft.mailing:
    class: Bigsoft\StoreBundle\Service\Mailing
    arguments: ['@mailer', '@templating', '%bigsoft.mailing.from_address%']
