Bigsoft\StoreBundle\Entity\Product:
  properties:
    title:
      - NotBlank: ~
      - Bigsoft\StoreBundle\Validator\Constraint\UniqueTitleConstraint: ~
    description:
      - NotBlank: ~
    imageUrl:
      - Url: ~
      - NotBlank: ~
    price:
      - NotBlank: ~
      - Range:
          min: 0
Bigsoft\StoreBundle\Entity\Order:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    name:
      - NotBlank: ~
    address:
      - NotBlank: ~