security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  firewalls:
    secured_area:
        pattern:    ^/
        anonymous: ~
        form_login: ~
        logout: ~
  providers:
    default_provider:
      memory:
        users:
          admin: {password: super-admin, roles: 'ROLE_ADMIN'}
  access_control:
    - { path: ^/product/(create|edit|delete), roles: ROLE_ADMIN }
    - { path: ^/logout, roles: ROLE_ADMIN }