Bigsoft\StoreBundle\Entity\Cart:
  type: entity
  table: carts
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  oneToMany:
    items:
      targetEntity: CartItem
      mappedBy: cart
