Bigsoft\StoreBundle\Entity\CartItem:
  type: entity
  table: cart_items
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    quantity:
      type: integer
  manyToOne:
    cart:
      targetEntity: Cart
      inversedBy: items
      joinColumn:
        cart_id:
          referencedColumnName: id
    product:
      targetEntity: Product
      joinColumn:
        product_id:
          referencedColumnName: id
